### ISSUE TITLE
Some code ideas 1

### ISSUE THREAD

**Issue by oniznorb** [myopengift/JGift_ios#1]
// This function is defined inside another function,  it works, but would be better moved  before function motion(event) 
		// that is because the function is being defined every time motion is called 
		
                function clip(num, min, max) {
			return num <= min ? min : num >= max ? max : num;
		}
		// end of function to move

**Comment by oniznorb** [comment]
/*

		Instead of lots of if statments  it is better to use switch.    
		If  imagerotation == 1 then only one if is evaluated.
		if imagerotation == 50 then if is evaluated 50 times -- this may slow your program down a lot

		if you use switch, then the switch is evaluated only once no matter what the value of imagerotation is 

        switch (imageRotation) {
            case 1:
                document.getElementById("myImage").src = 'gift_0001.png';
                break;
            case 2:
                document.getElementById("myImage").src = 'gift_0002.png';
				break;

			//etc....

*/

**Comment by oniznorb** [comment]
/*



		//a different way to do this may be to compute the image name,  something like this
		//but you may have to rename the image files  to gift_1.png, gift_2.png etc... 
		// or you could write a function which adds zeros to the number to pad it out to 4 characters


			var irot = imageRotation.toString();
			var gift = "gift_";
			var ping = ".png";

			var imgname  = gift.concat(irot).concat(ping);
			document.getElementById("myImage").src = imgname


        } 

*/

**Comment by myopengift** [comment]
I could use a batch rename. thanks for the comment... will have a look tomorrow.
